- name: Continuous Integration
  hosts: localhost
  connection: local

  tasks:
    - name: Update apt cache and install dependencies (Debian/Ubuntu)
      apt:
        update_cache: yes
        name:
          - python3-pip
          - jq
        state: present
      become: yes

    - set_fact:
        git_username: "{{ lookup('env', 'git_username') }}"
        git_password: "{{ lookup('env', 'git_password') }}"
        subscription_id: "{{ lookup('env', 'subscription_id') }}"
        service_principal_id: "{{ lookup('env', 'service_principal_id') }}"
        service_principal_secret: "{{ lookup('env', 'service_principal_secret') }}"
        acr_registry_url: "{{ lookup('env', 'acr_registry_url') }}"
        acr_username: "{{ lookup('env', 'acr_username') }}"
        tenant_id: "{{ lookup('env', 'tenant_id') }}"
        service_name: "{{ lookup('env', 'service_name') }}"
        source_dir: "{{ lookup('env', 'source_dir') }}"

    - name: Login to Azure using Service Principal
      command: >
        az login
        --service-principal
        --username '{{ service_principal_id }}'
        --password '{{ service_principal_secret }}'
        --tenant '{{ tenant_id }}'

    - name: Set subscription to current directory
      command: az account set --subscription {{ subscription_id }}

    - name: Login to ACR registry
      shell: echo "{{ service_principal_secret }}" | docker login wellfeddev.azurecr.io --username "{{ service_principal_id }}" --password-stdin

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{ source_dir }}/frontend/wellfed"

    - name: Read package.json
      command: cat {{ source_dir }}/frontend/wellfed/package.json
      register: package_json

    - name: Debug package.json content
      debug:
        var: package_json.stdout

    - name: Extract version from package.json using jq
      shell: echo '{{ package_json.stdout }}' | jq -r '.version'
      register: version_output

    - name: Debug extracted version
      debug:
        var: version_output.stdout

    - name: Set version and imagelabel fact
      set_fact:
        version: "{{ version_output.stdout }}"
        imagelabel: "{{ version_output.stdout }}"

    - name: Debug version and imagelabel
      debug:
        msg: "version: {{ version }}, imagelabel: {{ imagelabel }}"

    - name: Setup Docker buildx
      command: docker buildx create --use --platform linux/amd64,linux/arm64
      register: buildx_setup
      failed_when: buildx_setup.rc != 0

    - name: Build docker image for amd64 and arm64 and push to ACR
      command: docker buildx build --platform linux/amd64,linux/arm64 -t wellfeddev.azurecr.io/{{ service_name }}:{{ imagelabel }} --push .
      args:
        chdir: "{{ source_dir }}/frontend/wellfed"
      register: docker_build_result
      failed_when: docker_build_result.rc != 0

    - name: Debug Docker build result
      debug:
        msg: "{{ docker_build_result.stdout_lines }}"
