- name: Continuous Integration
  hosts: "localhost"
  connection: "local"

  vars:
    subscription_id: "{{ lookup('env', 'subscription_id') | default('4322c6c1-84a5-4760-bb72-9f56e2391033') }}"
    env_dir: "{{ lookup('env', 'env_dir') | default('/mnt/c/Users/velap/Documents/WellFed/frontend/wellfed/workspace') }}"
    git_username: "{{ lookup('env', 'git_username') | default('rithvikvelapati') }}"
    git_password: "{{ lookup('env', 'git_password') | default('default-password') }}"

  tasks:
  - debug:
      msg: "subscription_id: {{ subscription_id }}"

  - name: Login to Azure using Service Principal
    command: >
      az login

  - name: Set subscription to current directory
    command: >
      az account set --subscription {{ subscription_id }}

  - name: Clone Git repository
    git:
      repo: "https://{{ git_username }}:{{ git_password }}@wellfed.git"
      dest: "{{ env_dir }}"
