- name: Continuous Integration
  hosts: "localhost"
  connection: "local"

  tasks:
  - set_fact:
      git_username: "{{ lookup('env', 'git_username') }}"
      git_password: "{{ lookup('env', 'git_password') }}"
      subscription_id: "{{ lookup('env', 'subscription_id') }}"
      tenant_id: "{{ lookup('env', 'tenant_id') }}"
      env_dir: "{{ lookup('env', 'env_dir') }}"
      work_dir: "{{ lookup('env', 'work_dir') }}"  # Corrected from 'work' to 'env'

  - name: Login to Azure using Service Principal
    command: >
      az login

  - name: Set subscription to current directory
    command: >
      az account set --subscription {{ subscription_id }}

  - name: Clone Git repository
    git:
      repo: "https://{{ git_username }}:{{ git_password }}@wellfed.git"
      dest: "{{ env_dir }}"
