apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellfed-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wellfed-deploy
  template:
    metadata:
      labels:
        app: wellfed-deploy
    spec:
      containers:
      - name: wellfed-frontend
        image: '{{ acr_regisroty_url }}/wellfed-frontend:0.1.0'
        ports:
        - containerPort: 80