apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellfed-deploy
  namespace: wellfed-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wellfed-frontend
  template:
    metadata:
      labels:
        app: wellfed-frontend
    spec:
      containers:
      - name: wellfed-frontend
        image: wellfeddev.azurecr.io/wellfed-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: wellfed-secrets
              key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wellfed-secrets
              key: CLERK_SECRET_KEY
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "http://48.217.198.29"
        resources:
          request:
            cpu: "200m"
            memory: "350mi"
          limit:
            cpu: "250m"
            memory: "512mi"
      imagePullSecrets: 
      - name: acr-secret 
      restartPolicy: Always 
      schedulerName: default-scheduler 
      securityContext: {} 
      terminationGracePeriodSeconds: 30
