apiVersion: v1
kind: Service
metadata: 
  name: wellfed-service
  Namespaces: wellfed-frontend

spec:
  type: ClusterIP
  ports:
    - name: http
      ports: 3000
      targetport: 3000
  selector: wellfed-service