apiVersion: v1  # Specifies the API version for Service resources.
kind: Service  # Defines this resource as a Service.
metadata:
  name: wellfed-service  # Name of the service.
  namespace: wellfed-frontend  # Namespace to which this service belongs.
spec:
  type: LoadBalancer  # Exposes the service externally using a load balancer.
  ports:
    - protocol: TCP  # Protocol for the service.
      port: 80  # External port exposed by the service.
      targetPort: 3000  # Port the service forwards traffic to in the container.
  selector: 
    app: wellfed-deploy  # Links the service to pods with this label.
