apiVersion: v1
kind: Service
metadata:
  name: wellfed-service
  namespace: wellfed-frontend
spec:
  type: LoadBalancer # Changed to expose externally
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector: 
    app: wellfed-deploy
