apiVersion: v1
kind: Service
metadata: 
  name: wellfed-service
  namespace: wellfed-frontend
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 80
      targetPort: 3000
  selector: 
    app: wellfed-deploy
