trigger: none

pool:
   name: wellfedagent
   demands:
    - Agent.Name -equals ubuntu-agent

steps:

# - task: Bash@2
#   displayName: CHange directory permissions
#   inputs:
#     targetType: inline
#     script: |
#       chmod +x $(Agent.BuildDirectory)/scripts/

# Install Node.js
- task: Bash@2
  displayName: "Install Node.js"
  inputs:
    targetType: inline
    script: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      node --version
      npm --version

# Install Docker
- task: Bash@2
  displayName: "Install Docker"
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce
      sudo usermod -aG docker $(whoami)
      docker --version

# Install Python and pip
- task: Bash@2
  displayName: "Install Python and pip"
  inputs:
    targetType: inline
    script: |
      sudo apt-get install -y python3 python3-pip
      python3 --version
      pip3 --version

# Install Ansible
- task: Bash@2
  displayName: "Install Ansible"
  inputs:
    targetType: inline
    script: |
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
      ansible --version
