trigger:
  - main

pool:
  name: wellfedagent
  vmImage: wellfedagent # Ensure this matches the pool

steps:
  - task: UseNode@1
    inputs:
      version: "18.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm test
    displayName: "Install dependencies and run tests"
  # Install Docker
  - powershell: |
      # Install Docker on Windows
      Install-PackageProvider -Name NuGet -Force
      Install-Module -Name DockerMsftProvider -Repository PSGallery -Force
      Install-Package -Name docker -ProviderName DockerMsftProvider -Force
      Start-Service -Name docker
      docker --version
    displayName: 'Install Docker on Windows Agent'
  # Install Ansible
  - powershell: |
      # Install Python and Ansible via pip
      Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
      python get-pip.py
      pip install ansible
      ansible --version
    displayName: 'Install Ansible on Windows Agent'