name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger: none

pr: none

variables: 
  - group: wellfed-variablegroup

pool:
  name: wellfedagent
  vmImage: wellfedagent

steps:
  - script: |
      wsl --list --verbose
      wsl sudo apt-get update -y
      wsl sudo apt-get install -y ansible
      wsl ansible --version
    displayName: "Verify WSL and Install Dependencies"
  
  - task: Powershell@2
    displayName: "Run Ansible Playbook"
    env:
      git_username: "$(git_username)"
      git_password: "$(git_password)"
      subscription_id: "$(subscription_id)"
      tenant_id: "$(tenant_id)"
      env_dir: "$(Agent.BuildDirectory)/env"
      work_dir: "$(System.DefaultWorkingDirectory)/work"
    inputs:
      targetType: inline
      script: |
        wsl export git_username=${git_username}
        wsl export git_password=${git_password}
        wsl export subscription_id=${subscription_id}
        wsl export tenant_id=${tenant_id}
        wsl export env_dir=${env_dir}
        wsl export work_dir=${work_dir}
        wsl ansible-playbook /mnt/c/cicd/ansible/ci.yaml -i "localhost," -v
