name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger: none

pr: none

variables: 
  - group: wellfed-variablegroup

parameters:
  - name: version
    displayName: version
    type: string
    default: ''

pool:
  name: Azure Pipelines
  demands:
    - Agent.Name -equals Hosted Agent

steps:
  - task: Bash@3
    displayName: "Run Ansible Playbook"
    env:
      git_username: "$(git_username)"
      git_password: "$(git_password)"
      subscription_id: "$(subscription_id)"
      service_principal_id: "$(service_principal_id)"
      service_principal_secret: "$(service_principal_secret)"
      acr_registry_url: "$(acr_registry_url)"
      acr_username: "$(acr_username)"
      tenant_id: "$(tenant_id)"
      service_name: "$(service_name)"
      source_dir: "$(Build.SourcesDirectory)"
      aks_cluster: "$(aks_cluster)"
      resource_group: "$(resource_group)"
    inputs:
      targetType: inline
      script: |
        set -e  # Exit on error
        echo "Current Directory:"
        pwd
        cd ${source_dir}/frontend/wellfed
        echo "Current Directory after changing:"
        pwd
        echo "Directory Listing:"
        ls -lrt
        echo "Running Ansible Playbook:"
        ansible-playbook cicd/ansible/cd.yaml -i "localhost, " -v
