name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.SourceBranchName)

trigger: none

pr: none

variables: 
  - group: wellfed-variablegroup

pool:
  name: wellfedagent
  vmImage: wellfedagent

steps:
  - task: Powershell@2
    displayName: "Run Ansible Playbook"
    env:
      git_username: "$(git_username)"
      git_password: "$(git_password)"
      subscription_id: "$(subscription_id)"
      tenant_id: "$(tenant_id)"
      env_dir: "$(Agent.BuildDirectory)/env"
      work_dir: "$(System.DefaultWorkingDirectory)/work"
    inputs:
      targetType: "inline"
      script: |
        ansible-playbook cicd/ansible/ci.yaml -i "localhost, " -v
